package ca.uqam.mgl7460.tp3.ressources.drools;

unit PretsHypothecairesRuleUnitData;

import ca.uqam.mgl7460.tp3.ressources.types.domaine.Resultat;
import ca.uqam.mgl7460.tp3.ressources.types.processus.instances.InstanceProcessus;
import ca.uqam.mgl7460.tp3.ressources.types.processus.instances.EtatTraitement;
import ca.uqam.mgl7460.tp3.ressources.types.processus.instances.EtatProcessus;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.DemandePret;
