package ca.uqam.mgl7460.tp3.ressources.drools;

unit PretsHypothecairesRuleUnitData;

import ca.uqam.mgl7460.tp3.ressources.types.domaine.Propriete;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.ProvinceOuTerritoire;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.Resultat;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.DemandePret;
import java.util.Iterator;

rule "Désolés - votre demande a été refusée"
salience 10
when
	$demande: DemandePret(resultatTraitement.resultat == Resultat.REFUSEE)
then
    System.out.println("Nous sommes désolés: votre demande a été refusée");
	System.out.println("Exécution de la règle " + kcontext.getRule().getName());
end

rule "affichage des messages d'erreurs"
salience 1
when
	$demande: DemandePret(resultatTraitement.resultat == Resultat.REFUSEE, $messages : resultatTraitement.getMessages())
then
    while ($messages.hasNext()) {System.out.println("Erreur: " + $messages.next());};
	System.out.println("Exécution de la règle " + kcontext.getRule().getName());
end
