package ca.uqam.mgl7460.tp3.ressources.drools;

unit PretsHypothecairesRuleUnitData;

import ca.uqam.mgl7460.tp3.ressources.types.domaine.Resultat;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.Propriete;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.ProvinceOuTerritoire;
import ca.uqam.mgl7460.tp3.ressources.types.domaine.DemandePret;
import ca.uqam.mgl7460.tp3.ressources.types.processus.definitions.DefinitionTransition;
import ca.uqam.mgl7460.tp3.ressources.types.processus.definitions.DefinitionTache;
import ca.uqam.mgl7460.tp3.ressources.types.processus.instances.InstanceProcessus;

rule "Tranisition True"
when
    $transition: DefinitionTransition()
    eval(true)
then
     $transition.setIsPass(true);
end
